version: 0.0
os: linux
files:
  - source: /
    destination: /opt/dragons-counter
hooks:
  BeforeInstall:
    - location: scripts/codedeploy/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/codedeploy/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/codedeploy/application_start.sh
      timeout: 600
      runas: root
  ValidateService:
    - location: scripts/codedeploy/validate_service.sh
      timeout: 180
      runas: root
