SHELL := /bin/bash

PORT_FILE := .worktree-ports.txt
MAIN_WORKTREE := $(shell git worktree list --porcelain | head -1 | sed 's/worktree //')
CURRENT_DIR := $(shell pwd)
IS_WORKTREE := $(shell [ "$(MAIN_WORKTREE)" = "$(CURRENT_DIR)" ] && echo 0 || echo 1)

.PHONY: dev down status

## メイン: 開発環境の起動
## - メインworktree: そのまま起動（デフォルトポート使用）
## - サブworktree: .envコピー + ポート動的割り当て + 起動
dev:
ifeq ($(IS_WORKTREE),1)
	@test -f "$(MAIN_WORKTREE)/.env" || (echo "Error: $(MAIN_WORKTREE)/.env が存在しません" && exit 1)
	@test -f .env || (cp "$(MAIN_WORKTREE)/.env" .env && echo "✔ .env をメインworktreeからコピーしました")
	@$(MAKE) --no-print-directory _assign-ports
endif
	docker compose up -d
	@$(MAKE) --no-print-directory _record-ports
	@echo ""
	@echo "開発環境を起動しました:"
	@cat $(PORT_FILE)

## Docker停止
down:
	docker compose down

## 現在のポート割り当てを表示
status:
	@if [ -f $(PORT_FILE) ]; then \
		cat $(PORT_FILE); \
	else \
		echo "ポートファイルが見つかりません。'make dev' を実行してください。"; \
	fi

## サブworktree用: ポートオフセットを計算して.envに設定
## ポート衝突時はオフセットをずらしてリトライする（最大10回）
_assign-ports:
	@BASE_OFFSET=$$(echo "$(CURRENT_DIR)" | cksum | awk '{print ($$1 % 50 + 1) * 100}'); \
	FOUND=0; \
	for RETRY in $$(seq 0 9); do \
		OFFSET=$$(($$BASE_OFFSET + $$RETRY * 100)); \
		TEST_PORT=$$((3306 + $$OFFSET)); \
		if ! lsof -i :$$TEST_PORT -sTCP:LISTEN > /dev/null 2>&1; then \
			FOUND=1; \
			break; \
		fi; \
		echo "⚠ オフセット $$OFFSET はポート競合のためスキップ"; \
	done; \
	if [ $$FOUND -eq 0 ]; then \
		echo "Error: 空きポートが見つかりません" && exit 1; \
	fi; \
	grep -v -e '^HOST_.*_PORT=' -e '^# Worktree dynamic port' -e '^# proxyはメイン' .env > .env.tmp && mv .env.tmp .env; \
	{ \
		echo ""; \
		echo "# Worktree dynamic port settings (auto-generated by make dev)"; \
		echo "HOST_DB_PORT=$$((3306 + $$OFFSET))"; \
		echo "HOST_TEST_DB_PORT=$$((3307 + $$OFFSET))"; \
		echo "HOST_BACKEND_PORT=$$((3443 + $$OFFSET))"; \
		echo "HOST_FRONTEND_PORT=$$((3043 + $$OFFSET))"; \
		echo "HOST_API_DOCS_PORT=$$((8080 + $$OFFSET))"; \
		echo "# proxyはメインworktreeで特権ポート443を使用するため、サブworktreeでは8443を基準にする"; \
		echo "HOST_PROXY_PORT=$$((8443 + $$OFFSET))"; \
	} >> .env; \
	echo "✔ ポートオフセット: $$OFFSET を適用しました"

## ポート割り当てをファイルに記録
_record-ports:
	@{ \
		echo "# Dragons Counter - Port Assignment"; \
		echo "# Branch: $$(git branch --show-current)"; \
		echo "# Directory: $(CURRENT_DIR)"; \
		echo "# Generated: $$(date '+%Y-%m-%d %H:%M:%S')"; \
		echo ""; \
		for svc_port in "db 3306" "test-db 3306" "backend 3443" "frontend 3043" "api-docs 80" "proxy 443"; do \
			svc=$$(echo $$svc_port | cut -d' ' -f1); \
			port=$$(echo $$svc_port | cut -d' ' -f2); \
			host_port=$$(docker compose port $$svc $$port 2>/dev/null | cut -d: -f2); \
			if [ -n "$$host_port" ]; then \
				echo "$$svc: localhost:$$host_port"; \
			else \
				echo "$$svc: (not running)"; \
			fi; \
		done; \
	} > $(PORT_FILE)
