// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: games.sql

package sqlc

import (
	"context"
)

const getGameByID = `-- name: GetGameByID :one
SELECT id, game_date, opponent, dragons_score, opponent_score, result, stadium_id, created_at, updated_at FROM games
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetGameByID(ctx context.Context, id string) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGameByID, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.GameDate,
		&i.Opponent,
		&i.DragonsScore,
		&i.OpponentScore,
		&i.Result,
		&i.StadiumID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
