// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type GamesResult string

const (
	GamesResultWin  GamesResult = "win"
	GamesResultLose GamesResult = "lose"
	GamesResultDraw GamesResult = "draw"
)

func (e *GamesResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GamesResult(s)
	case string:
		*e = GamesResult(s)
	default:
		return fmt.Errorf("unsupported scan type for GamesResult: %T", src)
	}
	return nil
}

type NullGamesResult struct {
	GamesResult GamesResult `json:"games_result"`
	Valid       bool        `json:"valid"` // Valid is true if GamesResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGamesResult) Scan(value interface{}) error {
	if value == nil {
		ns.GamesResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GamesResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGamesResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GamesResult), nil
}

type UserRegistrationRequestsStatus string

const (
	UserRegistrationRequestsStatusPending  UserRegistrationRequestsStatus = "pending"
	UserRegistrationRequestsStatusApproved UserRegistrationRequestsStatus = "approved"
	UserRegistrationRequestsStatusRejected UserRegistrationRequestsStatus = "rejected"
	UserRegistrationRequestsStatusBanned   UserRegistrationRequestsStatus = "banned"
)

func (e *UserRegistrationRequestsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRegistrationRequestsStatus(s)
	case string:
		*e = UserRegistrationRequestsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRegistrationRequestsStatus: %T", src)
	}
	return nil
}

type NullUserRegistrationRequestsStatus struct {
	UserRegistrationRequestsStatus UserRegistrationRequestsStatus `json:"user_registration_requests_status"`
	Valid                          bool                           `json:"valid"` // Valid is true if UserRegistrationRequestsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRegistrationRequestsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserRegistrationRequestsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRegistrationRequestsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRegistrationRequestsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRegistrationRequestsStatus), nil
}

type UsersRole string

const (
	UsersRoleUser  UsersRole = "user"
	UsersRoleAdmin UsersRole = "admin"
)

func (e *UsersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersRole(s)
	case string:
		*e = UsersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersRole: %T", src)
	}
	return nil
}

type NullUsersRole struct {
	UsersRole UsersRole `json:"users_role"`
	Valid     bool      `json:"valid"` // Valid is true if UsersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersRole) Scan(value interface{}) error {
	if value == nil {
		ns.UsersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersRole), nil
}

type Game struct {
	ID            string      `json:"id"`
	GameDate      time.Time   `json:"game_date"`
	Opponent      string      `json:"opponent"`
	DragonsScore  int32       `json:"dragons_score"`
	OpponentScore int32       `json:"opponent_score"`
	Result        GamesResult `json:"result"`
	StadiumID     string      `json:"stadium_id"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type Stadium struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Role      UsersRole `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserRegistrationRequest struct {
	ID                 string                         `json:"id"`
	UserID             string                         `json:"user_id"`
	Status             UserRegistrationRequestsStatus `json:"status"`
	Reasonforrejection sql.NullString                 `json:"reasonforrejection"`
	CreatedAt          time.Time                      `json:"created_at"`
	UpdatedAt          time.Time                      `json:"updated_at"`
}

type UsersGame struct {
	ID         string         `json:"id"`
	UserID     string         `json:"user_id"`
	GameID     string         `json:"game_id"`
	Impression sql.NullString `json:"impression"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
}
