// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stadiums.sql

package sqlc

import (
	"context"
	"time"
)

const getStadiumByID = `-- name: GetStadiumByID :one
SELECT id, name, created_at, updated_at FROM stadiums
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetStadiumByID(ctx context.Context, id string) (Stadium, error) {
	row := q.db.QueryRowContext(ctx, getStadiumByID, id)
	var i Stadium
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStadiumByName = `-- name: GetStadiumByName :one
SELECT id, name, created_at, updated_at FROM stadiums
WHERE name = ?
LIMIT 1
`

func (q *Queries) GetStadiumByName(ctx context.Context, name string) (Stadium, error) {
	row := q.db.QueryRowContext(ctx, getStadiumByName, name)
	var i Stadium
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStadiums = `-- name: ListStadiums :many
SELECT id, name, created_at, updated_at FROM stadiums
ORDER BY name
`

func (q *Queries) ListStadiums(ctx context.Context) ([]Stadium, error) {
	rows, err := q.db.QueryContext(ctx, listStadiums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stadium{}
	for rows.Next() {
		var i Stadium
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStadium = `-- name: UpsertStadium :exec
INSERT INTO stadiums (id, name, created_at, updated_at)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE name = VALUES(name), updated_at = VALUES(updated_at)
`

type UpsertStadiumParams struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpsertStadium(ctx context.Context, arg UpsertStadiumParams) error {
	_, err := q.db.ExecContext(ctx, upsertStadium,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
