// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_registration_requests.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createRegistrationRequest = `-- name: CreateRegistrationRequest :exec
INSERT INTO user_registration_requests (id, user_id, status, reasonForRejection, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateRegistrationRequestParams struct {
	ID                 string                         `json:"id"`
	UserID             string                         `json:"user_id"`
	Status             UserRegistrationRequestsStatus `json:"status"`
	Reasonforrejection sql.NullString                 `json:"reasonforrejection"`
	CreatedAt          time.Time                      `json:"created_at"`
	UpdatedAt          time.Time                      `json:"updated_at"`
}

func (q *Queries) CreateRegistrationRequest(ctx context.Context, arg CreateRegistrationRequestParams) error {
	_, err := q.db.ExecContext(ctx, createRegistrationRequest,
		arg.ID,
		arg.UserID,
		arg.Status,
		arg.Reasonforrejection,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getLatestRegistrationByUserID = `-- name: GetLatestRegistrationByUserID :one
SELECT id, user_id, status, reasonforrejection, created_at, updated_at FROM user_registration_requests
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestRegistrationByUserID(ctx context.Context, userID string) (UserRegistrationRequest, error) {
	row := q.db.QueryRowContext(ctx, getLatestRegistrationByUserID, userID)
	var i UserRegistrationRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Reasonforrejection,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
