// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users_games.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createUserGame = `-- name: CreateUserGame :exec
INSERT INTO users_games (id, user_id, game_id, impression, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateUserGameParams struct {
	ID         string         `json:"id"`
	UserID     string         `json:"user_id"`
	GameID     string         `json:"game_id"`
	Impression sql.NullString `json:"impression"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

func (q *Queries) CreateUserGame(ctx context.Context, arg CreateUserGameParams) error {
	_, err := q.db.ExecContext(ctx, createUserGame,
		arg.ID,
		arg.UserID,
		arg.GameID,
		arg.Impression,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getUserGameByUserIDAndGameID = `-- name: GetUserGameByUserIDAndGameID :one
SELECT id, user_id, game_id, impression, created_at, updated_at, deleted_at FROM users_games
WHERE user_id = ? AND game_id = ? AND deleted_at IS NULL
LIMIT 1
`

type GetUserGameByUserIDAndGameIDParams struct {
	UserID string `json:"user_id"`
	GameID string `json:"game_id"`
}

func (q *Queries) GetUserGameByUserIDAndGameID(ctx context.Context, arg GetUserGameByUserIDAndGameIDParams) (UsersGame, error) {
	row := q.db.QueryRowContext(ctx, getUserGameByUserIDAndGameID, arg.UserID, arg.GameID)
	var i UsersGame
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameID,
		&i.Impression,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUserGamesByUserID = `-- name: ListUserGamesByUserID :many
SELECT id, user_id, game_id, impression, created_at, updated_at, deleted_at FROM users_games
WHERE user_id = ? AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListUserGamesByUserID(ctx context.Context, userID string) ([]UsersGame, error) {
	rows, err := q.db.QueryContext(ctx, listUserGamesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsersGame{}
	for rows.Next() {
		var i UsersGame
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GameID,
			&i.Impression,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreUserGame = `-- name: RestoreUserGame :exec
UPDATE users_games SET deleted_at = NULL, impression = ?, updated_at = ?
WHERE user_id = ? AND game_id = ?
`

type RestoreUserGameParams struct {
	Impression sql.NullString `json:"impression"`
	UpdatedAt  time.Time      `json:"updated_at"`
	UserID     string         `json:"user_id"`
	GameID     string         `json:"game_id"`
}

func (q *Queries) RestoreUserGame(ctx context.Context, arg RestoreUserGameParams) error {
	_, err := q.db.ExecContext(ctx, restoreUserGame,
		arg.Impression,
		arg.UpdatedAt,
		arg.UserID,
		arg.GameID,
	)
	return err
}

const softDeleteUserGame = `-- name: SoftDeleteUserGame :exec
UPDATE users_games SET deleted_at = ?, updated_at = ? WHERE id = ?
`

type SoftDeleteUserGameParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
}

func (q *Queries) SoftDeleteUserGame(ctx context.Context, arg SoftDeleteUserGameParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteUserGame, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}
